"use client";

import { useEffect, useRef, useState } from "react";
import { Plus, WalletCards, ArrowUpRight, ReceiptText, Users, Archive, Download, Upload, ArrowRight, Check, Trash2, RefreshCw, LogIn } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Skeleton } from "@/components/ui/skeleton";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { CURRENCIES, balances, suggestions, formatMoney } from "@/lib/domain.mjs";
import { Choice, Blank, today } from "./ledger-ui";
import { CreateForm, RepaymentForm, ImportForm } from "./ledger-forms";
import { ExpenseForm } from "./expense-form";
import { ExpenseList } from "./expense-list";
import { TripSettings } from "./trip-settings";
import { TeamPanel, JoinForm, roles } from "./team-panel";
import { RepaymentPanel } from "./repayment-panel";
import type { Trip, Repayment, Expense } from "@/lib/types";

class ApiError extends Error { constructor(message:string, public status:number, public mode="sites") {super(message);} }
async function api(path:string, data?:unknown) {
  const response=await fetch(`/api/${path}`,data===undefined?{cache:"no-store"}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
  const result=await response.json() as {error?:string;mode:string;trip:Trip;trips:Trip[];requests:{id:string;tripId:string;tripName:string;status:string}[];invitationToken?:string;left?:boolean;request?:{tripName:string;status:string}}; if(!response.ok)throw new ApiError(result.error??"無法完成操作",response.status,result.mode);return result;
}
export default function LedgerApp() {
  const [trips,setTrips]=useState<Trip[]>([]),[selected,setSelected]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[auth,setAuth]=useState<"sites"|"standalone"|null>(null),[mode,setMode]=useState("sites");
  const [tab,setTab]=useState("expenses"),[creating,setCreating]=useState(false),[adding,setAdding]=useState(false),[importing,setImporting]=useState(false),[repaying,setRepaying]=useState<(Partial<Repayment>&{id:string})|null>(null),[voiding,setVoiding]=useState<{action:string;id:string;title:string}|null>(null),[busy,setBusy]=useState(false);
  const [backupView,setBackupView]=useState<{filename:string;text:string}|null>(null);
  const [joining,setJoining]=useState(false),[incomingInvite,setIncomingInvite]=useState(''),[inviteLinks,setInviteLinks]=useState<Record<string,string>>({}),[requests,setRequests]=useState<{id:string;tripName:string;status:string}[]>([]);
  useEffect(()=>{const token=new URLSearchParams(window.location.hash.slice(1)).get('join');if(token){setIncomingInvite(token);setJoining(true);}},[]);
  const [editing,setEditing]=useState<Expense|null>(null),[managing,setManaging]=useState(false),[tripScope,setTripScope]=useState("active"),[actionError,setActionError]=useState(""),[offline,setOffline]=useState(false);
  useEffect(()=>{const update=()=>setOffline(!navigator.onLine);update();window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update);};},[]);
  const [formTripSnapshot,setFormTripSnapshot]=useState<Trip|null>(null);
  const formTrip=trips.find(t=>t.id===formTripSnapshot?.id)??(formTripSnapshot?{...formTripSnapshot,me:{...formTripSnapshot.me,role:'viewer' as const}}:null);
  const captureTrip=()=>{setActionError("");setFormTripSnapshot(currentRef.current??null);};
  const visibleTrips=trips.filter(t=>tripScope==="all"||(tripScope==="archived"?t.archived:!t.archived));
  const current=visibleTrips.find(t=>t.id===selected)??visibleTrips[0], currentRef=useRef<Trip|undefined>(current), tripsRef=useRef(trips);currentRef.current=current;tripsRef.current=trips;
  const syncEpoch=useRef(0),busyRef=useRef(false);
  const sync=async()=>{const epoch=++syncEpoch.current;try{const result=await api("state");if(epoch!==syncEpoch.current)return;setTrips(result.trips);setRequests(result.requests??[]);setMode(result.mode);setAuth(null);setError("");}catch(e){if(epoch!==syncEpoch.current)return;if(e instanceof ApiError&&e.status===401){setAuth(e.mode as "sites"|"standalone");setTrips([]);}else setError(e instanceof Error?e.message:"暫時無法讀取帳目");}finally{setLoading(false);}};
  useEffect(()=>{void sync();},[]);
  useEffect(()=>{const update=()=>{if(document.visibilityState==='visible'&&!busyRef.current)void sync();};const timer=setInterval(update,15000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update);};},[]);
  useEffect(()=>{
    const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
    if(!context?.registerTool)return;const lifecycle=new AbortController();
    const tools=[
      {name:"read_trip_balances",title:"讀取目前旅程餘額",description:"讀取畫面所選旅程的旅伴、支出總額與含已記錄還款的餘額，不變更資料。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("此工具不接受參數");const t=currentRef.current;if(!t)throw new Error("請先建立或選擇旅程");const b=balances(t);return {tripId:t.id,name:t.name,currency:t.currency,minorUnitDigits:CURRENCIES[t.currency as keyof typeof CURRENCIES],members:t.members.map(m=>({...m,balance:b[m.id]}))};}},
      {name:"start_expense_entry",title:"開啟記帳表單",description:"開啟目前旅程的新增支出表單。這個操作不會儲存帳目，需填寫並送出表單。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("此工具不接受參數");if(!currentRef.current)throw new Error("請先建立旅程");if(currentRef.current.archived||currentRef.current.me.role==="viewer")throw new Error("此旅程目前無法新增支出");captureTrip();setAdding(true);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {opened:true,tripId:currentRef.current.id};}},
    ];
    for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return()=>lifecycle.abort();
  },[]);
  const changed=(trip:Trip)=>{setTripScope(trip.archived?"archived":"active");setActionError("");setTrips(old=>[trip,...old.filter(t=>t.id!==trip.id)]);setSelected(trip.id);};
  const run=async(work:()=>Promise<void>)=>{if(busyRef.current)return;busyRef.current=true;syncEpoch.current++;setBusy(true);setActionError("");try{await work();}catch(e){const message=e instanceof Error?e.message:"無法完成操作";setActionError(message);toast.error(message);if(e instanceof ApiError&&[401,403,404,409].includes(e.status))await sync();}finally{busyRef.current=false;setBusy(false);}};
  const mutate=async(action:string,data:unknown,target:Trip|null|undefined=current)=>{if(!target)throw new Error("請先選擇旅程");const result=await api(`trips/${target.id}/${action}`,{revision:target.revision,...(data as object)});changed(result.trip);};
  const download=()=>run(async()=>{if(!current)return;const backup=await api(`trips/${current.id}/backup`),url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`tripledger-${current.id}-${today()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast.success("備份已準備，請確認瀏覽器是否已儲存檔案");});
  const viewBackup=()=>run(async()=>{if(!current)return;const backup=await api(`trips/${current.id}/backup`);setBackupView({filename:`tripledger-${current.id}-${today()}.json`,text:JSON.stringify(backup,null,2)});});
  const b=current?balances(current):{},total=current?current.expenses.filter(e=>!e.voided).reduce((s,e)=>s+e.amount,0):0,owed=Object.values(b).reduce((s:number,v)=>s+Math.max(0,v as number),0),money=(n:number)=>current?formatMoney(n,current.currency):"—",name=(id:string)=>current?.members.find(m=>m.id===id)?.name??"未知旅伴";
  const expenses=current?[...current.expenses].reverse():[], repayments=current?[...current.repayments].reverse():[];
  const admin=current?.me.role==='admin',canWrite=!!current&&current.me.role!=='viewer'&&!current.archived;
  const teamAction=(action:string,data:unknown)=>run(async()=>{if(!current)return;const result=await api(`trips/${current.id}/${action}`,{revision:current.revision,...data as object});if(result.left){await sync();return;}changed(result.trip);if(result.invitationToken)setInviteLinks(old=>({...old,[current.id]:`${window.location.origin}/#join=${result.invitationToken}`}));if(action==='revoke-invite')setInviteLinks(old=>({...old,[current.id]:''}));toast.success('成員設定已更新');});
  return <div className="app-shell">
    <Toaster position="top-center" richColors/>
    <header className="topbar"><a className="brand" href="/"><span className="brand-icon"><WalletCards size={23}/></span><span>TripLedger<small>旅伴帳本</small></span></a><div className="row"><span className="pill">{mode==="standalone"?"自主託管":"內部測試"}</span>{!auth&&!loading&&<button className="icon-button" aria-label="重新整理帳目" onClick={()=>void sync()}><RefreshCw size={18}/></button>}</div></header>
    <main className="workspace">
      <div className="page-heading"><div><p className="eyebrow">TRAVEL TOGETHER · SPLIT SIMPLY</p><h1>{current?.name??"每段旅程，都算清楚。"}</h1><p className="muted">{current?`${current.members.length} 位旅伴 · ${current.currency} · ${roles[current.me.role]}${current.team.enabled?" · 共同記帳":""}`:"把共同支出留在這裡，好好享受旅途。"}</p></div>{!auth&&<button className="primary" onClick={()=>{captureTrip();current?setAdding(true):setCreating(true);}} disabled={loading||!!current&&!canWrite||busy}><Plus size={19}/>{current?"新增支出":"建立旅程"}</button>}</div>
      {offline&&<p className="notice" role="status">目前離線，表單可繼續填寫；恢復連線後請再儲存。尚未送出的內容不會自動同步。</p>}
      {current?.archived&&admin&&<div className="notice"><span>此旅程已封存，仍可查看帳目與備份。</span><button className="secondary" onClick={()=>{captureTrip();setManaging(true);}}>管理／解除封存</button></div>}
      {error&&<div className="error" role="alert">{error}<button className="secondary" onClick={()=>void sync()}>重試</button></div>}
      {loading?<div className="summary-grid"><Skeleton className="h-44 rounded-2xl"/><Skeleton className="h-44 rounded-2xl"/><Skeleton className="h-44 rounded-2xl"/></div>:auth?<section className="panel"><Blank icon={<LogIn size={30}/>} title="登入你的旅伴帳本" description={auth==="sites"?"登入後，旅程與帳目會保存到你的私人帳本。":"使用自架伺服器設定的密碼開啟帳本。"}>{auth==="sites"?<a className="primary" href={`/signin-with-chatgpt?return_to=${encodeURIComponent(incomingInvite?`/#join=${incomingInvite}`:"/")}`}>使用 ChatGPT 登入</a>:<form className="form-stack" onSubmit={e=>{e.preventDefault();const password=String(new FormData(e.currentTarget).get("password"));void run(async()=>{await api("login",{password});await sync();});}}><label className="field">帳本密碼<input name="password" type="password" required autoComplete="current-password"/></label><button className="primary" disabled={busy}>開啟帳本</button></form>}</Blank></section>:<>
      {trips.length>0&&<div className="trip-bar"><Choice label="旅程範圍" value={tripScope} options={[{value:"active",label:"進行中"},{value:"archived",label:"已封存"},{value:"all",label:"全部旅程"}]} onChange={setTripScope}/>{current&&<Choice label="目前旅程" value={current.id} options={visibleTrips.map(t=>({value:t.id,label:t.name}))} onChange={setSelected}/>}<button className="secondary" onClick={()=>{setActionError("");setCreating(true);}}>新旅程</button>{current&&admin&&<button className="secondary" onClick={()=>{captureTrip();setManaging(true);}}>管理旅程</button>}</div>}
      {mode!=="standalone"&&<div className="join-bar"><button className="secondary" onClick={()=>{setActionError("");setJoining(true);}}>使用邀請加入帳本</button><span className="small muted">每 15 秒更新，也可按右上角重新整理。</span></div>}{requests.filter(r=>r.status!=="approved").map(r=><p className="notice" key={r.id}>{r.tripName}：{r.status==="pending"?"已送出申請，等待管理者核准":"申請未通過或邀請已撤銷"}</p>)}<div className="summary-grid"><section className="summary-card hero-card"><span>旅程總支出</span><strong>{money(total)}</strong><span className="hero-foot">{current?`${current.expenses.filter(e=>!e.voided).length} 筆共同支出`:"從第一筆共同支出開始"}<ArrowUpRight size={20}/></span></section><section className="summary-card"><span className="muted">旅伴</span><strong>{current?.members.length??0} <small>位</small></strong><span className="muted">{current?current.members.map(m=>m.name).join("、"):"一起出發，一起分擔"}</span></section><section className="summary-card"><span className="muted">尚待結清</span><strong>{money(owed)}</strong><span className="muted">{current&&owed===0&&total>0?"目前帳目已結清":"只扣除已確認還款"}</span></section></div>
      <Tabs value={tab} onValueChange={setTab}><TabsList className="view-tabs"><TabsTrigger value="expenses"><ReceiptText/>支出紀錄</TabsTrigger><TabsTrigger value="balances"><Users/>分攤與還款</TabsTrigger><TabsTrigger value="team"><Users/>共同記帳</TabsTrigger><TabsTrigger value="backup"><Archive/>備份</TabsTrigger></TabsList>
      <TabsContent value="expenses"><section className="panel">{!current?<Blank title={tripScope==="archived"?"尚無封存旅程":"建立一段新旅程"} description="選擇其他旅程範圍，或建立旅程開始記帳。"><button className="primary" onClick={()=>setCreating(true)}>建立旅程</button></Blank>:!expenses.length?<Blank icon={<ReceiptText size={30}/>} title="這段旅程還沒有支出" description="住宿、車票或晚餐，都可以在這裡記錄。">{canWrite&&<button className="primary" onClick={()=>{captureTrip();setAdding(true);}}>記一筆支出</button>}</Blank>:<ExpenseList key={current.id} trip={current} busy={busy} onEdit={e=>{captureTrip();setEditing(e);}} onVoid={e=>{captureTrip();setVoiding({action:"void-expense",id:e.id,title:e.title});}}/>}</section></TabsContent>
      <TabsContent value="balances">{current?<RepaymentPanel trip={current} busy={busy} onCreate={r=>{captureTrip();setRepaying(r);}} onVoid={r=>{captureTrip();setVoiding({action:"void-repayment",id:r.id,title:"這筆已確認還款"});}} onAction={(action,data)=>void run(async()=>{await mutate(action,data,current);toast.success("還款處理已儲存");})}/>:<section className="panel"><Blank title="選擇帳本查看分攤" description="建立旅程或使用邀請加入帳本。"/></section>}</TabsContent>
      <TabsContent value="team">{current?<TeamPanel key={current.id} trip={current} mode={mode} busy={busy} inviteLink={inviteLinks[current.id]??''} send={teamAction}/>:<section className="panel"><Blank title="一起記錄旅途支出" description="建立帳本後可邀請成員；收到邀請也可從上方申請加入。"/></section>}</TabsContent>
      <TabsContent value="backup"><section className="panel backup-panel"><div><span className="empty-icon"><Archive size={28}/></span><h2>你的帳目，隨時帶走。</h2><p className="muted">下載目前旅程的完整備份，包含旅伴、支出、分攤、還款，以及實際儲存的收據圖片與操作歷史。</p><p className="small muted">每個旅程分別備份；備份可還原到 TripLedger 的 Sites 或自架版本。匯入會建立旅程，不會覆蓋現有資料；原成員須重新邀請。只有管理者能匯出完整備份。</p><div className="backup-actions"><button className="primary" disabled={!current||!admin||busy} onClick={()=>void download()}><Download size={18}/>下載此旅程備份</button><button className="secondary" disabled={!current||!admin||busy} onClick={()=>void viewBackup()}>檢視完整備份</button><button className="secondary" onClick={()=>setImporting(true)} disabled={busy}><Upload size={18}/>匯入備份</button></div></div><aside><h3>這一版的範圍</h3><ul><li>每個旅程使用一種幣別</li><li>2–20 位旅伴，支援邀請共同記帳</li><li>最多 300 筆支出、200 筆還款</li><li>收據每張 1 MB，旅程合計 8 MB</li></ul><p>備份內含完整帳務與收據，請保存在自己的安全位置。</p></aside></section></TabsContent>
      </Tabs></>}
      <footer>TripLedger · 旅途一起走，帳目輕鬆記。</footer>
    </main>
    <Dialog open={joining&&!auth&&!loading} onOpenChange={open=>!busy&&setJoining(open)}><DialogContent className="ledger-dialog"><DialogTitle>申請加入帳本</DialogTitle><DialogDescription>使用管理者提供的邀請，登入後提出申請。</DialogDescription>{actionError&&<p className="error" role="alert">{actionError}</p>}{joining&&<JoinForm initial={incomingInvite} busy={busy} submit={token=>run(async()=>{const result=await api("join",{id:crypto.randomUUID(),token});setJoining(false);setIncomingInvite('');window.history.replaceState(null,'',window.location.pathname+window.location.search);await sync();toast.success(result.request?.status==='pending'?"申請已送出，請等待管理者核准":"此邀請已處理");})}/>}</DialogContent></Dialog>
    <Dialog open={!!editing} onOpenChange={open=>!busy&&!open&&setEditing(null)}><DialogContent className="ledger-dialog"><DialogTitle>更正支出</DialogTitle><DialogDescription>{formTrip?.name} · 更正後會重新計算餘額</DialogDescription>{actionError&&<p className="error" role="alert">{actionError} · 輸入仍保留</p>}{editing&&formTrip&&<ExpenseForm key={editing.id} trip={formTrip} expense={editing} busy={busy} submit={data=>run(async()=>{await mutate("edit-expense",data,formTrip);setEditing(null);toast.success("更正已儲存，原始內容保留於歷史");})}/>}</DialogContent></Dialog>
    <Dialog open={managing} onOpenChange={open=>!busy&&setManaging(open)}><DialogContent className="ledger-dialog"><DialogTitle>管理旅程</DialogTitle><DialogDescription>整理旅程名稱與封存狀態，所有帳目都會保留。</DialogDescription>{actionError&&<p className="error" role="alert">{actionError}</p>}{managing&&formTrip&&<TripSettings key={formTrip.id} trip={formTrip} busy={busy} submit={(action,data)=>run(async()=>{await mutate(action,data,formTrip);setManaging(false);toast.success("旅程已更新");})}/>}</DialogContent></Dialog>
    <Dialog open={creating} onOpenChange={setCreating}><DialogContent className="ledger-dialog"><DialogTitle>建立旅程</DialogTitle><DialogDescription>加入這次一起分攤的旅伴。旅伴名稱是帳務標記，不會寄出邀請。</DialogDescription>{creating&&<CreateForm busy={busy} submit={data=>run(async()=>{changed((await api("trips",data)).trip);setCreating(false);setTab("expenses");toast.success("旅程已建立");})}/>}</DialogContent></Dialog>
    <Dialog open={adding} onOpenChange={open=>!busy&&setAdding(open)}><DialogContent className="ledger-dialog"><DialogTitle>記一筆支出</DialogTitle><DialogDescription>{formTrip?.name} · {formTrip?.currency}</DialogDescription>{actionError&&<p className="error" role="alert">{actionError} · 輸入仍保留</p>}{adding&&formTrip&&<ExpenseForm trip={formTrip} busy={busy} submit={data=>run(async()=>{await mutate("expense",data,formTrip);setAdding(false);setTab("expenses");toast.success("支出已儲存");})}/>}</DialogContent></Dialog>
    <Dialog open={!!repaying} onOpenChange={open=>!busy&&!open&&setRepaying(null)}><DialogContent className="ledger-dialog"><DialogTitle>{formTrip?.team.enabled?"申報已付款":"記錄已還款"}</DialogTitle><DialogDescription>{repaying&&`${(formTrip?.members.find(m=>m.id===repaying.fromId)?.name??"")} → ${(formTrip?.members.find(m=>m.id===repaying.toId)?.name??"")}`}，只申報已實際完成的款項。</DialogDescription>{actionError&&<p className="error" role="alert">{actionError} · 輸入仍保留</p>}{repaying&&formTrip&&<RepaymentForm key={repaying.id} trip={formTrip} draft={repaying} busy={busy} submit={data=>run(async()=>{await mutate("repayment",data,formTrip);setRepaying(null);toast.success(formTrip.team.enabled?"還款已申報，等待收款方確認":"還款已記錄，餘額已更新");})}/>}</DialogContent></Dialog>
    <Dialog open={importing} onOpenChange={setImporting}><DialogContent className="ledger-dialog"><DialogTitle>匯入旅程備份</DialogTitle><DialogDescription>選擇 TripLedger 匯出的 JSON 完整備份。若同一旅程已存在，系統會拒絕覆蓋。</DialogDescription>{importing&&<ImportForm busy={busy} submit={data=>run(async()=>{changed((await api("import",data)).trip);setImporting(false);setTab("expenses");toast.success("旅程與收據已完整還原");})}/>}</DialogContent></Dialog>
    <Dialog open={!!backupView} onOpenChange={open=>!open&&setBackupView(null)}><DialogContent className="ledger-dialog"><DialogTitle>完整旅程備份</DialogTitle><DialogDescription>若瀏覽器無法下載，請複製全部內容，以 UTF-8 純文字另存為 .json 檔。內容包含帳務與收據原檔。</DialogDescription>{backupView&&<div className="form-stack"><p className="small muted break-all">建議檔名：{backupView.filename}</p><label className="field">完整備份 JSON<textarea readOnly value={backupView.text} spellCheck={false} style={{height:"40dvh",fontFamily:"monospace",fontSize:12}} onFocus={e=>e.currentTarget.select()}/></label><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(backupView.text);toast.success("完整備份已複製");}catch{toast.error("瀏覽器無法自動複製，請在內容欄位全選後手動複製");}}}>複製全部內容</button></div>}</DialogContent></Dialog>
    <AlertDialog open={!!voiding} onOpenChange={open=>!open&&setVoiding(null)}><AlertDialogContent className="ledger-dialog"><AlertDialogTitle>作廢這筆紀錄？</AlertDialogTitle><AlertDialogDescription>「{voiding?.title}」將不再計入餘額。原始紀錄與收據仍會保留，方便日後核對。支出若只是填寫錯誤，也可以取消並使用更正功能。</AlertDialogDescription>{formTrip&&formTripSnapshot&&formTrip.revision!==formTripSnapshot.revision&&<div className="notice"><p>帳本已有更新，請核對目前紀錄後再作廢：{formTrip.expenses.find(e=>e.id===voiding?.id)?.title??"還款紀錄"}。</p><button className="secondary" onClick={()=>setFormTripSnapshot(formTrip)}>已核對最新帳本，繼續作廢</button></div>}<AlertDialogFooter><AlertDialogCancel>保留紀錄</AlertDialogCancel><AlertDialogAction disabled={busy||formTrip?.me.role==="viewer"||formTrip?.revision!==formTripSnapshot?.revision} onClick={e=>{e.preventDefault();void run(async()=>{if(!voiding)return;await mutate(voiding.action,{id:voiding.id,operationId:crypto.randomUUID(),revision:formTripSnapshot?.revision},formTrip);setVoiding(null);toast.success("紀錄已作廢");});}}>確認作廢</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
