"use client";

import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { Plus, WalletCards, ArrowUpRight, MapPin, ReceiptText, Users, Archive, Download, Upload, ArrowRight, Check, Paperclip, Trash2, RefreshCw, LogIn, Utensils, TrainFront, BedDouble, ShoppingBag, Ellipsis } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Skeleton } from "@/components/ui/skeleton";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { CURRENCIES, LIMITS, balances, suggestions, formatMoney, parseMoney, evenShares } from "@/lib/domain.mjs";
import type { Trip, Repayment } from "@/lib/types";

const today = () => { const date = new Date(); return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,10); };
const categories = { "餐飲":Utensils,"交通":TrainFront,"住宿":BedDouble,"購物":ShoppingBag,"其他":Ellipsis };
class ApiError extends Error { constructor(message:string, public status:number, public mode="sites") {super(message);} }
async function api(path:string, data?:unknown) {
  const response=await fetch(`/api/${path}`,data===undefined?{cache:"no-store"}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
  const result=await response.json() as {error?:string;mode:string;trip:Trip;trips:Trip[]}; if(!response.ok)throw new ApiError(result.error??"無法完成操作",response.status,result.mode);return result;
}
function Choice({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(value:string)=>void}) {
  return <div className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="select-control"><SelectValue placeholder="請選擇"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;
}
function Blank({icon=<MapPin size={30}/>,title,description,children}:{icon?:ReactNode;title:string;description:string;children?:ReactNode}) {
  return <Empty className="empty-state"><EmptyHeader><span className="empty-icon">{icon}</span><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{children}</Empty>;
}
async function imagePayload(file:File|null) {
  if(!file)return undefined;
  if(file.size>LIMITS.receiptBytes)throw new Error("每張收據上限為 1 MB，請先縮小圖片");
  if(!["image/png","image/jpeg","image/webp"].includes(file.type))throw new Error("請選擇 JPG、PNG 或 WebP 收據");
  const bytes=new Uint8Array(await file.arrayBuffer());let text="";for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return {mime:file.type,data:btoa(text)};
}

export default function LedgerApp() {
  const [trips,setTrips]=useState<Trip[]>([]),[selected,setSelected]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[auth,setAuth]=useState<"sites"|"standalone"|null>(null),[mode,setMode]=useState("sites");
  const [tab,setTab]=useState("expenses"),[creating,setCreating]=useState(false),[adding,setAdding]=useState(false),[importing,setImporting]=useState(false),[repaying,setRepaying]=useState<(Partial<Repayment>&{id:string})|null>(null),[voiding,setVoiding]=useState<{action:string;id:string;title:string}|null>(null),[busy,setBusy]=useState(false);
  const current=trips.find(t=>t.id===selected)??trips[0], currentRef=useRef<Trip|undefined>(current), tripsRef=useRef(trips);currentRef.current=current;tripsRef.current=trips;
  const sync=async()=>{try{const result=await api("state");setTrips(result.trips);setMode(result.mode);setAuth(null);setError("");}catch(e){if(e instanceof ApiError&&e.status===401){setAuth(e.mode as "sites"|"standalone");setTrips([]);}else setError(e instanceof Error?e.message:"暫時無法讀取帳目");}finally{setLoading(false);}};
  useEffect(()=>{void sync();},[]);
  useEffect(()=>{
    const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
    if(!context?.registerTool)return;const lifecycle=new AbortController();
    const tools=[
      {name:"read_trip_balances",title:"讀取目前旅程餘額",description:"讀取畫面所選旅程的旅伴、支出總額與含已記錄還款的餘額，不變更資料。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("此工具不接受參數");const t=currentRef.current;if(!t)throw new Error("請先建立或選擇旅程");const b=balances(t);return {tripId:t.id,name:t.name,currency:t.currency,minorUnitDigits:CURRENCIES[t.currency as keyof typeof CURRENCIES],members:t.members.map(m=>({...m,balance:b[m.id]}))};}},
      {name:"start_expense_entry",title:"開啟記帳表單",description:"開啟目前旅程的新增支出表單。這個操作不會儲存帳目，需填寫並送出表單。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("此工具不接受參數");if(!currentRef.current)throw new Error("請先建立旅程");setAdding(true);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {opened:true,tripId:currentRef.current.id};}},
    ];
    for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return()=>lifecycle.abort();
  },[]);
  const changed=(trip:Trip)=>{setTrips(old=>[trip,...old.filter(t=>t.id!==trip.id)]);setSelected(trip.id);};
  const run=async(work:()=>Promise<void>)=>{setBusy(true);try{await work();}catch(e){toast.error(e instanceof Error?e.message:"無法完成操作");if(e instanceof ApiError&&e.status===409)await sync();}finally{setBusy(false);}};
  const mutate=async(action:string,data:unknown)=>{if(!current)throw new Error("請先選擇旅程");const result=await api(`trips/${current.id}/${action}`,{...(data as object),revision:current.revision});changed(result.trip);};
  const download=()=>run(async()=>{if(!current)return;const backup=await api(`trips/${current.id}/backup`),url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`tripledger-${current.id}-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast.success("完整備份已下載，包含旅程、帳目、還款與收據");});
  const b=current?balances(current):{},total=current?current.expenses.filter(e=>!e.voided).reduce((s,e)=>s+e.amount,0):0,owed=Object.values(b).reduce((s:number,v)=>s+Math.max(0,v as number),0),money=(n:number)=>current?formatMoney(n,current.currency):"—",name=(id:string)=>current?.members.find(m=>m.id===id)?.name??"未知旅伴";
  const expenses=current?[...current.expenses].reverse():[], repayments=current?[...current.repayments].reverse():[];
  return <div className="app-shell">
    <Toaster position="top-center" richColors/>
    <header className="topbar"><a className="brand" href="/"><span className="brand-icon"><WalletCards size={23}/></span><span>TripLedger<small>旅伴帳本</small></span></a><div className="row"><span className="pill">{mode==="standalone"?"自主託管":"內部測試"}</span>{!auth&&!loading&&<button className="icon-button" aria-label="重新整理帳目" onClick={()=>void sync()}><RefreshCw size={18}/></button>}</div></header>
    <main className="workspace">
      <div className="page-heading"><div><p className="eyebrow">TRAVEL TOGETHER · SPLIT SIMPLY</p><h1>{current?.name??"每段旅程，都算清楚。"}</h1><p className="muted">{current?`${current.members.length} 位旅伴 · ${current.currency} · 由你統一記帳`:"把共同支出留在這裡，好好享受旅途。"}</p></div>{!auth&&<button className="primary" onClick={()=>current?setAdding(true):setCreating(true)} disabled={loading}><Plus size={19}/>{current?"新增支出":"建立旅程"}</button>}</div>
      {error&&<div className="error" role="alert">{error}<button className="secondary" onClick={()=>void sync()}>重試</button></div>}
      {loading?<div className="summary-grid"><Skeleton className="h-44 rounded-2xl"/><Skeleton className="h-44 rounded-2xl"/><Skeleton className="h-44 rounded-2xl"/></div>:auth?<section className="panel"><Blank icon={<LogIn size={30}/>} title="登入你的旅伴帳本" description={auth==="sites"?"登入後，旅程與帳目會保存到你的私人帳本。":"使用自架伺服器設定的密碼開啟帳本。"}>{auth==="sites"?<a className="primary" href="/signin-with-chatgpt?return_to=%2F">使用 ChatGPT 登入</a>:<form className="form-stack" onSubmit={e=>{e.preventDefault();const password=String(new FormData(e.currentTarget).get("password"));void run(async()=>{await api("login",{password});await sync();});}}><label className="field">帳本密碼<input name="password" type="password" required autoComplete="current-password"/></label><button className="primary" disabled={busy}>開啟帳本</button></form>}</Blank></section>:<>
      {trips.length>0&&<div className="trip-bar"><Choice label="目前旅程" value={current?.id??""} options={trips.map(t=>({value:t.id,label:t.name}))} onChange={setSelected}/><button className="secondary" onClick={()=>setCreating(true)}><Plus size={17}/>新旅程</button></div>}
      <div className="summary-grid"><section className="summary-card hero-card"><span>旅程總支出</span><strong>{money(total)}</strong><span className="hero-foot">{current?`${current.expenses.filter(e=>!e.voided).length} 筆共同支出`:"從第一筆共同支出開始"}<ArrowUpRight size={20}/></span></section><section className="summary-card"><span className="muted">旅伴</span><strong>{current?.members.length??0} <small>位</small></strong><span className="muted">{current?current.members.map(m=>m.name).join("、"):"一起出發，一起分擔"}</span></section><section className="summary-card"><span className="muted">尚待結清</span><strong>{money(owed)}</strong><span className="muted">{current&&owed===0&&total>0?"目前帳目已結清":"已扣除記錄的還款"}</span></section></div>
      <Tabs value={tab} onValueChange={setTab}><TabsList className="view-tabs"><TabsTrigger value="expenses"><ReceiptText/>支出紀錄</TabsTrigger><TabsTrigger value="balances"><Users/>分攤與還款</TabsTrigger><TabsTrigger value="backup"><Archive/>備份</TabsTrigger></TabsList>
      <TabsContent value="expenses"><section className="panel">{!current?<Blank title="下一站，去哪裡？" description="建立旅程並加入旅伴，就能開始記錄共同支出。"><button className="primary" onClick={()=>setCreating(true)}><Plus size={18}/>建立第一個旅程</button></Blank>:!expenses.length?<Blank icon={<ReceiptText size={30}/>} title="第一筆支出，從這裡開始" description="誰先付了住宿、車票或晚餐？記下來，帳本會幫你算好每個人的分攤。"><button className="primary" onClick={()=>setAdding(true)}><Plus size={18}/>記一筆支出</button></Blank>:<><div className="section-head"><h2>旅途中的每一筆</h2><span className="small muted">{expenses.filter(e=>!e.voided).length} 筆有效支出</span></div><div className="expense-list">{expenses.map(e=>{const Icon=categories[e.category as keyof typeof categories];return <article className={`expense-row ${e.voided?"voided":""}`} key={e.id}><span className={`category-icon category-${Object.keys(categories).indexOf(e.category)}`}><Icon size={22}/></span><div className="expense-info"><h3>{e.title} {e.voided&&<span className="pill">已作廢</span>}</h3><p>{e.date.replaceAll("-","/")} · {name(e.payerId)} 先付 · {e.shares.length} 人分攤</p><details><summary>查看分攤</summary><div className="share-detail">{e.shares.map(s=><span key={s.memberId}>{name(s.memberId)} <b>{money(s.amount)}</b></span>)}</div></details>{e.receipt&&<a className="receipt-link" href={`/api/trips/${current.id}/receipts/${e.receipt.id}`} target="_blank" rel="noreferrer"><Paperclip size={13}/>查看收據</a>}</div><div className="expense-amount"><strong>{money(e.amount)}</strong><span>{e.category}</span></div>{!e.voided&&<button className="icon-button remove-expense" aria-label={`作廢支出：${e.title}`} onClick={()=>setVoiding({action:"void-expense",id:e.id,title:e.title})}><Trash2 size={16}/></button>}</article>;})}</div></>}</section></TabsContent>
      <TabsContent value="balances">{!current?<section className="panel"><Blank icon={<Users size={30}/>} title="一起分擔，輕鬆結清" description="建立旅程後，就能查看每位旅伴的分攤與還款。"/></section>:<div className="balance-layout"><section className="panel"><div className="section-head"><h2>旅伴餘額</h2><span className="small muted">含已記錄還款</span></div>{current.members.map((m,i)=><div className="member-row" key={m.id}><span className={`avatar avatar-${i%4}`}>{m.name.slice(0,1)}</span><div className="member-name"><b>{m.name}</b><small>{b[m.id]>0?"應收回":b[m.id]<0?"應付出":"已結清"}</small></div><strong className={b[m.id]>0?"positive":b[m.id]<0?"negative":"muted"}>{money(Math.abs(b[m.id]))}</strong></div>)}</section><section className="panel"><div className="section-head"><h2>建議還款</h2><span className="pill">{suggestions(current).length} 筆</span></div>{suggestions(current).length?suggestions(current).map((r:Omit<Repayment,"id"|"date"|"voided">)=><div className="suggestion" key={`${r.fromId}-${r.toId}`}><div className="row"><span>{name(r.fromId)} <ArrowRight size={14} className="inline"/> {name(r.toId)}</span><b>{money(r.amount)}</b></div><button className="secondary" onClick={()=>setRepaying({...r,id:crypto.randomUUID()})}><Check size={16}/>記錄已還款</button></div>):<div className="settled"><Check size={30}/><p>{total?"目前帳目已結清":"目前沒有待還款項"}</p></div>}<p className="small muted">實際收到款項後再記錄。這裡只保存還款紀錄。</p></section><section className="panel repayment-panel"><h2>還款紀錄</h2>{repayments.length?repayments.map(r=><div className={`repayment-row ${r.voided?"voided":""}`} key={r.id}><div><b>{name(r.fromId)} → {name(r.toId)}</b><small>{r.date} {r.voided?"· 已作廢":"· 已記錄"}</small></div><strong>{money(r.amount)}</strong>{!r.voided&&<button className="icon-button" aria-label={`作廢 ${name(r.fromId)} 的還款`} onClick={()=>setVoiding({action:"void-repayment",id:r.id,title:`${name(r.fromId)} → ${name(r.toId)} 的還款`})}><Trash2 size={16}/></button>}</div>):<p className="muted small mt-4">還沒有還款紀錄。</p>}</section></div>}</TabsContent>
      <TabsContent value="backup"><section className="panel backup-panel"><div><span className="empty-icon"><Archive size={28}/></span><h2>你的帳目，隨時帶走。</h2><p className="muted">下載目前旅程的完整備份，包含旅伴、支出、分攤、還款，以及收據原檔。</p><p className="small muted">每個旅程分別備份；備份可還原到 TripLedger 的 Sites 或自架版本。匯入會建立旅程，不會覆蓋現有資料。</p><div className="backup-actions"><button className="primary" disabled={!current||busy} onClick={()=>void download()}><Download size={18}/>下載此旅程備份</button><button className="secondary" onClick={()=>setImporting(true)} disabled={busy}><Upload size={18}/>匯入備份</button></div></div><aside><h3>這一版的範圍</h3><ul><li>每個旅程使用一種幣別</li><li>2–20 位旅伴，由你統一記帳</li><li>最多 300 筆支出、200 筆還款</li><li>收據每張 1 MB，旅程合計 8 MB</li></ul><p>備份內含完整帳務與收據，請保存在自己的安全位置。</p></aside></section></TabsContent>
      </Tabs></>}
      <footer>TripLedger · 旅途一起走，帳目輕鬆記。</footer>
    </main>
    <Dialog open={creating} onOpenChange={setCreating}><DialogContent className="ledger-dialog"><DialogTitle>建立旅程</DialogTitle><DialogDescription>加入這次一起分攤的旅伴。旅伴名稱是帳務標記，不會寄出邀請。</DialogDescription>{creating&&<CreateForm busy={busy} submit={data=>run(async()=>{changed((await api("trips",data)).trip);setCreating(false);setTab("expenses");toast.success("旅程已建立");})}/>}</DialogContent></Dialog>
    <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="ledger-dialog"><DialogTitle>記一筆支出</DialogTitle><DialogDescription>{current?.name} · {current?.currency}</DialogDescription>{adding&&current&&<ExpenseForm trip={current} busy={busy} submit={data=>run(async()=>{await mutate("expense",data);setAdding(false);setTab("expenses");toast.success("支出已儲存");})}/>}</DialogContent></Dialog>
    <Dialog open={!!repaying} onOpenChange={open=>!open&&setRepaying(null)}><DialogContent className="ledger-dialog"><DialogTitle>記錄已還款</DialogTitle><DialogDescription>{repaying&&`${name(repaying.fromId??"")} → ${name(repaying.toId??"")}`}，僅記錄已實際完成的款項。</DialogDescription>{repaying&&current&&<RepaymentForm key={repaying.id} trip={current} draft={repaying} busy={busy} submit={data=>run(async()=>{await mutate("repayment",data);setRepaying(null);toast.success("還款已記錄，餘額已更新");})}/>}</DialogContent></Dialog>
    <Dialog open={importing} onOpenChange={setImporting}><DialogContent className="ledger-dialog"><DialogTitle>匯入旅程備份</DialogTitle><DialogDescription>選擇 TripLedger 匯出的 JSON 完整備份。若同一旅程已存在，系統會拒絕覆蓋。</DialogDescription>{importing&&<ImportForm busy={busy} submit={data=>run(async()=>{changed((await api("import",data)).trip);setImporting(false);setTab("expenses");toast.success("旅程與收據已完整還原");})}/>}</DialogContent></Dialog>
    <AlertDialog open={!!voiding} onOpenChange={open=>!open&&setVoiding(null)}><AlertDialogContent className="ledger-dialog"><AlertDialogTitle>作廢這筆紀錄？</AlertDialogTitle><AlertDialogDescription>「{voiding?.title}」將不再計入餘額。原始紀錄與收據仍會保留，方便日後核對；需要更正時，可重新新增一筆。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>保留紀錄</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void run(async()=>{if(!voiding)return;await mutate(voiding.action,{id:voiding.id});setVoiding(null);toast.success("紀錄已作廢");});}}>確認作廢</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}

function CreateForm({busy,submit}:{busy:boolean;submit:(data:unknown)=>Promise<void>}) {
  const [id]=useState(()=>crypto.randomUUID()),[currency,setCurrency]=useState("TWD");
  return <form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit({id,name:f.get("name"),currency,members:String(f.get("members")).split(/\r?\n/).map(s=>s.trim()).filter(Boolean)});}}><label className="field">旅程名稱<input name="name" placeholder="例如：台南週末小旅行" maxLength={60} required autoFocus/></label><Choice label="記帳幣別" value={currency} options={Object.keys(CURRENCIES).map(c=>({value:c,label:c}))} onChange={setCurrency}/><label className="field">旅伴名稱<textarea name="members" placeholder={"每行一位，例如：\n小安\n小宇\n我"} required maxLength={820}/><small>2–20 位，名稱不可重複。這一版建立後固定旅伴與幣別。</small></label><button className="primary" disabled={busy}>{busy?"正在儲存…":"建立旅程"}</button></form>;
}
function ExpenseForm({trip,busy,submit}:{trip:Trip;busy:boolean;submit:(data:unknown)=>Promise<void>}) {
  const [id]=useState(()=>crypto.randomUUID()),[payer,setPayer]=useState(trip.members[0].id),[category,setCategory]=useState("餐飲"),[mode,setMode]=useState("equal"),[selected,setSelected]=useState(trip.members.map(m=>m.id)),[amount,setAmount]=useState(""),[file,setFile]=useState<File|null>(null),[exact,setExact]=useState<Record<string,string>>({}),[error,setError]=useState("");
  let preview:{memberId:string;amount:number}[]=[];try{if(mode==="equal")preview=evenShares(parseMoney(amount,trip.currency),selected);}catch{}
  const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError("");const form=new FormData(e.currentTarget);try{const total=parseMoney(amount,trip.currency),shares=selected.map(memberId=>({memberId,amount:mode==="exact"?(Number(exact[memberId])===0?0:parseMoney(exact[memberId]??"",trip.currency)):0}));if(mode==="exact"&&shares.reduce((s,x)=>s+x.amount,0)!==total)throw new Error("指定金額加總必須等於支出金額");if(!selected.length)throw new Error("請至少選擇一位分攤旅伴");await submit({id,title:form.get("title"),amount:total,payerId:payer,category,date:form.get("date"),mode,memberIds:selected,shares,file:await imagePayload(file)});}catch(e){setError(e instanceof Error?e.message:"請確認資料");}};
  return <form className="form-stack" onSubmit={e=>void save(e)}><label className="field">支出名稱<input name="title" required maxLength={80} placeholder="例如：旅程第一頓晚餐" autoFocus/></label><div className="form-row"><label className="field">金額（{trip.currency}）<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required placeholder={trip.currency==="JPY"?"0":"0.00"}/></label><label className="field">日期<input name="date" type="date" defaultValue={today()} required/></label></div><div className="form-row"><Choice label="誰先付款" value={payer} options={trip.members.map(m=>({value:m.id,label:m.name}))} onChange={setPayer}/><Choice label="分類" value={category} options={Object.keys(categories).map(c=>({value:c,label:c}))} onChange={setCategory}/></div><Choice label="分攤方式" value={mode} options={[{value:"equal",label:"平均分攤"},{value:"exact",label:"指定金額"}]} onChange={setMode}/><fieldset className="split-members"><legend>誰一起分攤</legend>{trip.members.map(m=><div className="split-row" key={m.id}><label><Checkbox checked={selected.includes(m.id)} onCheckedChange={checked=>setSelected(old=>checked?trip.members.filter(x=>x.id===m.id||old.includes(x.id)).map(x=>x.id):old.filter(id=>id!==m.id))}/>{m.name}</label>{selected.includes(m.id)&&(mode==="exact"?<input aria-label={`${m.name} 分攤金額`} inputMode="decimal" value={exact[m.id]??""} placeholder="0" onChange={e=>setExact(old=>({...old,[m.id]:e.target.value}))}/>:<span>{formatMoney(preview.find(s=>s.memberId===m.id)?.amount??0,trip.currency)}</span>)}</div>)}</fieldset><label className="field">收據圖片（選填）<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/><small>JPG、PNG 或 WebP，每張上限 1 MB。</small></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?"正在儲存…":"儲存支出"}</button></form>;
}
function RepaymentForm({trip,draft,busy,submit}:{trip:Trip;draft:Partial<Repayment>&{id:string};busy:boolean;submit:(data:unknown)=>Promise<void>}) {
  const digits=CURRENCIES[trip.currency as keyof typeof CURRENCIES],[amount,setAmount]=useState(((draft.amount??0)/10**digits).toFixed(digits)),[error,setError]=useState("");
  return <form className="form-stack" onSubmit={e=>{e.preventDefault();setError("");try{const f=new FormData(e.currentTarget);void submit({...draft,amount:parseMoney(amount,trip.currency),date:f.get("date")});}catch(e){setError(e instanceof Error?e.message:"");}}}><label className="field">實際還款金額（{trip.currency}）<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required autoFocus/><small>可記錄部分還款，最多 {formatMoney(draft.amount??0,trip.currency)}。</small></label><label className="field">還款日期<input name="date" type="date" defaultValue={today()} required/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>確認已實際還款</button></form>;
}
function ImportForm({busy,submit}:{busy:boolean;submit:(data:unknown)=>Promise<void>}) {
  const [backup,setBackup]=useState<{trip?:{name?:string;currency?:string;expenses?:unknown[]}}|null>(null),[error,setError]=useState("");
  return <form className="form-stack" onSubmit={e=>{e.preventDefault();if(backup)void submit(backup);}}><label className="field">備份檔案<input type="file" accept=".json,application/json" required onChange={async e=>{setBackup(null);setError("");try{const file=e.target.files?.[0];if(!file)return;if(file.size>LIMITS.bodyBytes)throw new Error("備份檔案上限為 14 MB");const data=JSON.parse(await file.text());if(data.format!=="tripledger-backup"||data.schemaVersion!==1)throw new Error("這不是支援的 TripLedger 備份");setBackup(data);}catch(e){setError(e instanceof Error?e.message:"無法讀取備份");}}}/></label>{backup&&<p className="muted">{backup.trip?.name} · {backup.trip?.currency} · {backup.trip?.expenses?.length??0} 筆支出<br/>收據與資料會在儲存前進行完整性檢查。</p>}{error&&<p className="error">{error}</p>}<button className="primary" disabled={!backup||busy}>{busy?"正在驗證與還原…":"驗證並匯入旅程"}</button></form>;
}
