"use client";
import { useState } from "react";
import { CURRENCIES, LIMITS, parseMoney, formatMoney, balances } from "@/lib/domain.mjs";
import type { Trip, Repayment } from "@/lib/types";
import { Choice, today } from "./ledger-ui";

export function CreateForm({busy,submit}:{busy:boolean;submit:(data:unknown)=>Promise<void>}) {
  const [id]=useState(()=>crypto.randomUUID()),[currency,setCurrency]=useState("TWD");
  return <form className="form-stack dialog-main-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit({id,name:f.get("name"),currency,members:String(f.get("members")).split(/\r?\n/).map(s=>s.trim()).filter(Boolean)});}}><label className="field">旅程名稱<input name="name" placeholder="例如：台南週末小旅行" maxLength={60} required autoFocus/></label><Choice label="記帳幣別" value={currency} options={Object.keys(CURRENCIES).map(c=>({value:c,label:c}))} onChange={setCurrency}/><label className="field">旅伴名稱<textarea name="members" placeholder={"每行一位，例如：\n小安\n小宇\n我"} required maxLength={820}/><small>建立時填入 2–20 位，名稱不可重複。之後可在「管理旅程」新增、改名、移除或恢復旅伴；幣別不可更改。</small></label><button className="primary" disabled={busy}>{busy?"正在儲存…":"建立旅程"}</button></form>;
}
export function RepaymentForm({trip,draft,busy,submit}:{trip:Trip;draft:Partial<Repayment>&{id:string};busy:boolean;submit:(data:unknown)=>Promise<void>}) {
  const digits=CURRENCIES[trip.currency as keyof typeof CURRENCIES],[amount,setAmount]=useState(((draft.amount??0)/10**digits).toFixed(digits)),[error,setError]=useState("");
  const [revision,setRevision]=useState(trip.revision),stale=revision!==trip.revision,b=balances(trip),pending=trip.repayments.filter(r=>r.status==='pending');
  const available=Math.max(0,Math.min(-(b[draft.fromId??'']??0)-pending.filter(r=>r.fromId===draft.fromId).reduce((s,r)=>s+r.amount,0),(b[draft.toId??'']??0)-pending.filter(r=>r.toId===draft.toId).reduce((s,r)=>s+r.amount,0)));
  const allowed=!trip.archived&&trip.me.role!=='viewer'&&(trip.me.role==='admin'||trip.me.participantId===draft.fromId);
  return <form className="form-stack dialog-main-form" onSubmit={e=>{e.preventDefault();setError("");try{if(stale||!allowed)throw new Error('請先核對最新帳目與權限');const f=new FormData(e.currentTarget);void submit({...draft,revision,amount:parseMoney(amount,trip.currency),date:f.get("date")});}catch(e){setError(e instanceof Error?e.message:"");}}}>{stale&&<div className="notice"><p>帳本已有更新，輸入仍保留。目前最多可申報 {formatMoney(available,trip.currency)}。</p><button type="button" className="secondary" onClick={()=>setRevision(trip.revision)}>已核對，使用最新版本</button></div>}{!allowed&&<p className="notice">目前沒有申報權限，或旅程已封存。輸入仍保留。</p>}<label className="field">實際還款金額（{trip.currency}）<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required autoFocus/><small>扣除待確認申報後，最多 {formatMoney(available,trip.currency)}。</small></label><label className="field">還款日期<input name="date" type="date" defaultValue={today()} required/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy||stale||!allowed}>{trip.team.enabled?'申報已付款，請收款方確認':'確認已實際還款'}</button></form>;
}
export function ImportForm({busy,submit}:{busy:boolean;submit:(data:unknown)=>Promise<void>}) {
  const [backup,setBackup]=useState<{trip?:{name?:string;currency?:string;expenses?:unknown[]}}|null>(null),[error,setError]=useState("");
  return <form className="form-stack dialog-main-form" onSubmit={e=>{e.preventDefault();if(backup)void submit(backup);}}><label className="field">備份檔案<input type="file" accept=".json,application/json" required onChange={async e=>{setBackup(null);setError("");try{const file=e.target.files?.[0];if(!file)return;if(file.size>LIMITS.bodyBytes)throw new Error("備份檔案上限為 14 MB");const data=JSON.parse(await file.text());if(data.format!=="tripledger-backup"||![1,2,3,4,5,6].includes(data.schemaVersion))throw new Error("這不是支援的 TripLedger 備份");setBackup(data);}catch(e){setError(e instanceof Error?e.message:"無法讀取備份");}}}/></label>{backup&&<p className="muted">{backup.trip?.name} · {backup.trip?.currency} · {backup.trip?.expenses?.length??0} 筆支出<br/>收據與資料會在儲存前進行完整性檢查。</p>}{error&&<p className="error">{error}</p>}<button className="primary" disabled={!backup||busy}>{busy?"正在驗證與還原…":"驗證並匯入旅程"}</button></form>;
}
