"use client";

import { useEffect, useRef, useState } from "react";
import { Plus, WalletCards, ArrowUpRight, ReceiptText, Users, Archive, Download, Upload, ArrowRight, Check, Trash2, RefreshCw, LogIn } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Skeleton } from "@/components/ui/skeleton";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { CURRENCIES, balances, suggestions, formatMoney } from "@/lib/domain.mjs";
import { Choice, Blank, today } from "./ledger-ui";
import { CreateForm, RepaymentForm, ImportForm } from "./ledger-forms";
import { ExpenseForm } from "./expense-form";
import { ExpenseList } from "./expense-list";
import { TripSettings } from "./trip-settings";
import type { Trip, Repayment, Expense } from "@/lib/types";

class ApiError extends Error { constructor(message:string, public status:number, public mode="sites") {super(message);} }
async function api(path:string, data?:unknown) {
  const response=await fetch(`/api/${path}`,data===undefined?{cache:"no-store"}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
  const result=await response.json() as {error?:string;mode:string;trip:Trip;trips:Trip[]}; if(!response.ok)throw new ApiError(result.error??"無法完成操作",response.status,result.mode);return result;
}
export default function LedgerApp() {
  const [trips,setTrips]=useState<Trip[]>([]),[selected,setSelected]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[auth,setAuth]=useState<"sites"|"standalone"|null>(null),[mode,setMode]=useState("sites");
  const [tab,setTab]=useState("expenses"),[creating,setCreating]=useState(false),[adding,setAdding]=useState(false),[importing,setImporting]=useState(false),[repaying,setRepaying]=useState<(Partial<Repayment>&{id:string})|null>(null),[voiding,setVoiding]=useState<{action:string;id:string;title:string}|null>(null),[busy,setBusy]=useState(false);
  const [backupView,setBackupView]=useState<{filename:string;text:string}|null>(null);
  const [editing,setEditing]=useState<Expense|null>(null),[managing,setManaging]=useState(false),[tripScope,setTripScope]=useState("active"),[actionError,setActionError]=useState(""),[offline,setOffline]=useState(false);
  useEffect(()=>{const update=()=>setOffline(!navigator.onLine);update();window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update);};},[]);
  const [formTripSnapshot,setFormTripSnapshot]=useState<Trip|null>(null);
  const formTrip=trips.find(t=>t.id===formTripSnapshot?.id)??formTripSnapshot;
  const captureTrip=()=>{setActionError("");setFormTripSnapshot(currentRef.current??null);};
  const visibleTrips=trips.filter(t=>tripScope==="all"||(tripScope==="archived"?t.archived:!t.archived));
  const current=visibleTrips.find(t=>t.id===selected)??visibleTrips[0], currentRef=useRef<Trip|undefined>(current), tripsRef=useRef(trips);currentRef.current=current;tripsRef.current=trips;
  const sync=async()=>{try{const result=await api("state");setTrips(result.trips);setMode(result.mode);setAuth(null);setError("");}catch(e){if(e instanceof ApiError&&e.status===401){setAuth(e.mode as "sites"|"standalone");setTrips([]);}else setError(e instanceof Error?e.message:"暫時無法讀取帳目");}finally{setLoading(false);}};
  useEffect(()=>{void sync();},[]);
  useEffect(()=>{
    const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
    if(!context?.registerTool)return;const lifecycle=new AbortController();
    const tools=[
      {name:"read_trip_balances",title:"讀取目前旅程餘額",description:"讀取畫面所選旅程的旅伴、支出總額與含已記錄還款的餘額，不變更資料。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("此工具不接受參數");const t=currentRef.current;if(!t)throw new Error("請先建立或選擇旅程");const b=balances(t);return {tripId:t.id,name:t.name,currency:t.currency,minorUnitDigits:CURRENCIES[t.currency as keyof typeof CURRENCIES],members:t.members.map(m=>({...m,balance:b[m.id]}))};}},
      {name:"start_expense_entry",title:"開啟記帳表單",description:"開啟目前旅程的新增支出表單。這個操作不會儲存帳目，需填寫並送出表單。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("此工具不接受參數");if(!currentRef.current)throw new Error("請先建立旅程");if(currentRef.current.archived)throw new Error("旅程已封存，請先解除封存");captureTrip();setAdding(true);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {opened:true,tripId:currentRef.current.id};}},
    ];
    for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return()=>lifecycle.abort();
  },[]);
  const changed=(trip:Trip)=>{setTripScope(trip.archived?"archived":"active");setActionError("");setTrips(old=>[trip,...old.filter(t=>t.id!==trip.id)]);setSelected(trip.id);};
  const run=async(work:()=>Promise<void>)=>{setBusy(true);setActionError("");try{await work();}catch(e){const message=e instanceof Error?e.message:"無法完成操作";setActionError(message);toast.error(message);if(e instanceof ApiError&&e.status===409)await sync();}finally{setBusy(false);}};
  const mutate=async(action:string,data:unknown,target:Trip|null|undefined=current)=>{if(!target)throw new Error("請先選擇旅程");const result=await api(`trips/${target.id}/${action}`,{revision:target.revision,...(data as object)});changed(result.trip);};
  const download=()=>run(async()=>{if(!current)return;const backup=await api(`trips/${current.id}/backup`),url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`tripledger-${current.id}-${today()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast.success("備份已準備，請確認瀏覽器是否已儲存檔案");});
  const viewBackup=()=>run(async()=>{if(!current)return;const backup=await api(`trips/${current.id}/backup`);setBackupView({filename:`tripledger-${current.id}-${today()}.json`,text:JSON.stringify(backup,null,2)});});
  const b=current?balances(current):{},total=current?current.expenses.filter(e=>!e.voided).reduce((s,e)=>s+e.amount,0):0,owed=Object.values(b).reduce((s:number,v)=>s+Math.max(0,v as number),0),money=(n:number)=>current?formatMoney(n,current.currency):"—",name=(id:string)=>current?.members.find(m=>m.id===id)?.name??"未知旅伴";
  const expenses=current?[...current.expenses].reverse():[], repayments=current?[...current.repayments].reverse():[];
  return <div className="app-shell">
    <Toaster position="top-center" richColors/>
    <header className="topbar"><a className="brand" href="/"><span className="brand-icon"><WalletCards size={23}/></span><span>TripLedger<small>旅伴帳本</small></span></a><div className="row"><span className="pill">{mode==="standalone"?"自主託管":"內部測試"}</span>{!auth&&!loading&&<button className="icon-button" aria-label="重新整理帳目" onClick={()=>void sync()}><RefreshCw size={18}/></button>}</div></header>
    <main className="workspace">
      <div className="page-heading"><div><p className="eyebrow">TRAVEL TOGETHER · SPLIT SIMPLY</p><h1>{current?.name??"每段旅程，都算清楚。"}</h1><p className="muted">{current?`${current.members.length} 位旅伴 · ${current.currency} · 由你統一記帳`:"把共同支出留在這裡，好好享受旅途。"}</p></div>{!auth&&<button className="primary" onClick={()=>{captureTrip();current?setAdding(true):setCreating(true);}} disabled={loading||current?.archived||busy}><Plus size={19}/>{current?"新增支出":"建立旅程"}</button>}</div>
      {offline&&<p className="notice" role="status">目前離線，表單可繼續填寫；恢復連線後請再儲存。尚未送出的內容不會自動同步。</p>}
      {current?.archived&&<div className="notice"><span>此旅程已封存，仍可查看帳目與備份。</span><button className="secondary" onClick={()=>{captureTrip();setManaging(true);}}>管理／解除封存</button></div>}
      {error&&<div className="error" role="alert">{error}<button className="secondary" onClick={()=>void sync()}>重試</button></div>}
      {loading?<div className="summary-grid"><Skeleton className="h-44 rounded-2xl"/><Skeleton className="h-44 rounded-2xl"/><Skeleton className="h-44 rounded-2xl"/></div>:auth?<section className="panel"><Blank icon={<LogIn size={30}/>} title="登入你的旅伴帳本" description={auth==="sites"?"登入後，旅程與帳目會保存到你的私人帳本。":"使用自架伺服器設定的密碼開啟帳本。"}>{auth==="sites"?<a className="primary" href="/signin-with-chatgpt?return_to=%2F">使用 ChatGPT 登入</a>:<form className="form-stack" onSubmit={e=>{e.preventDefault();const password=String(new FormData(e.currentTarget).get("password"));void run(async()=>{await api("login",{password});await sync();});}}><label className="field">帳本密碼<input name="password" type="password" required autoComplete="current-password"/></label><button className="primary" disabled={busy}>開啟帳本</button></form>}</Blank></section>:<>
      {trips.length>0&&<div className="trip-bar"><Choice label="旅程範圍" value={tripScope} options={[{value:"active",label:"進行中"},{value:"archived",label:"已封存"},{value:"all",label:"全部旅程"}]} onChange={setTripScope}/>{current&&<Choice label="目前旅程" value={current.id} options={visibleTrips.map(t=>({value:t.id,label:t.name}))} onChange={setSelected}/>}<button className="secondary" onClick={()=>{setActionError("");setCreating(true);}}>新旅程</button>{current&&<button className="secondary" onClick={()=>{captureTrip();setManaging(true);}}>管理旅程</button>}</div>}
      <div className="summary-grid"><section className="summary-card hero-card"><span>旅程總支出</span><strong>{money(total)}</strong><span className="hero-foot">{current?`${current.expenses.filter(e=>!e.voided).length} 筆共同支出`:"從第一筆共同支出開始"}<ArrowUpRight size={20}/></span></section><section className="summary-card"><span className="muted">旅伴</span><strong>{current?.members.length??0} <small>位</small></strong><span className="muted">{current?current.members.map(m=>m.name).join("、"):"一起出發，一起分擔"}</span></section><section className="summary-card"><span className="muted">尚待結清</span><strong>{money(owed)}</strong><span className="muted">{current&&owed===0&&total>0?"目前帳目已結清":"已扣除記錄的還款"}</span></section></div>
      <Tabs value={tab} onValueChange={setTab}><TabsList className="view-tabs"><TabsTrigger value="expenses"><ReceiptText/>支出紀錄</TabsTrigger><TabsTrigger value="balances"><Users/>分攤與還款</TabsTrigger><TabsTrigger value="backup"><Archive/>備份</TabsTrigger></TabsList>
      <TabsContent value="expenses"><section className="panel">{!current?<Blank title={tripScope==="archived"?"尚無封存旅程":"建立一段新旅程"} description="選擇其他旅程範圍，或建立旅程開始記帳。"><button className="primary" onClick={()=>setCreating(true)}>建立旅程</button></Blank>:!expenses.length?<Blank icon={<ReceiptText size={30}/>} title="這段旅程還沒有支出" description="住宿、車票或晚餐，都可以在這裡記錄。">{!current.archived&&<button className="primary" onClick={()=>{captureTrip();setAdding(true);}}>記一筆支出</button>}</Blank>:<ExpenseList key={current.id} trip={current} busy={busy} onEdit={e=>{captureTrip();setEditing(e);}} onVoid={e=>{captureTrip();setVoiding({action:"void-expense",id:e.id,title:e.title});}}/>}</section></TabsContent>
      <TabsContent value="balances">{!current?<section className="panel"><Blank icon={<Users size={30}/>} title="一起分擔，輕鬆結清" description="建立旅程後，就能查看每位旅伴的分攤與還款。"/></section>:<div className="balance-layout"><section className="panel"><div className="section-head"><h2>旅伴餘額</h2><span className="small muted">含已記錄還款</span></div>{current.members.map((m,i)=><div className="member-row" key={m.id}><span className={`avatar avatar-${i%4}`}>{m.name.slice(0,1)}</span><div className="member-name"><b>{m.name}</b><small>{b[m.id]>0?"應收回":b[m.id]<0?"應付出":"已結清"}</small></div><strong className={b[m.id]>0?"positive":b[m.id]<0?"negative":"muted"}>{money(Math.abs(b[m.id]))}</strong></div>)}</section><section className="panel"><div className="section-head"><h2>建議還款</h2><span className="pill">{suggestions(current).length} 筆</span></div>{suggestions(current).length?suggestions(current).map((r:Omit<Repayment,"id"|"date"|"voided">)=><div className="suggestion" key={`${r.fromId}-${r.toId}`}><div className="row"><span>{name(r.fromId)} <ArrowRight size={14} className="inline"/> {name(r.toId)}</span><b>{money(r.amount)}</b></div><button className="secondary" disabled={current.archived||busy} onClick={()=>{captureTrip();setRepaying({...r,id:crypto.randomUUID()});}}><Check size={16}/>記錄已還款</button></div>):<div className="settled"><Check size={30}/><p>{total?"目前帳目已結清":"目前沒有待還款項"}</p></div>}<p className="small muted">實際收到款項後再記錄。這裡只保存還款紀錄。</p></section><section className="panel repayment-panel"><h2>還款紀錄</h2>{repayments.length?repayments.map(r=><div className={`repayment-row ${r.voided?"voided":""}`} key={r.id}><div><b>{name(r.fromId)} → {name(r.toId)}</b><small>{r.date} {r.voided?"· 已作廢":"· 已記錄"}</small></div><strong>{money(r.amount)}</strong>{!r.voided&&!current.archived&&<button className="icon-button" aria-label={`作廢 ${name(r.fromId)} 的還款`} onClick={()=>{captureTrip();setVoiding({action:"void-repayment",id:r.id,title:`${name(r.fromId)} → ${name(r.toId)} 的還款`});}}><Trash2 size={16}/></button>}</div>):<p className="muted small mt-4">還沒有還款紀錄。</p>}</section></div>}</TabsContent>
      <TabsContent value="backup"><section className="panel backup-panel"><div><span className="empty-icon"><Archive size={28}/></span><h2>你的帳目，隨時帶走。</h2><p className="muted">下載目前旅程的完整備份，包含旅伴、支出、分攤、還款，以及收據原檔。</p><p className="small muted">每個旅程分別備份；備份可還原到 TripLedger 的 Sites 或自架版本。匯入會建立旅程，不會覆蓋現有資料。</p><div className="backup-actions"><button className="primary" disabled={!current||busy} onClick={()=>void download()}><Download size={18}/>下載此旅程備份</button><button className="secondary" disabled={!current||busy} onClick={()=>void viewBackup()}>檢視完整備份</button><button className="secondary" onClick={()=>setImporting(true)} disabled={busy}><Upload size={18}/>匯入備份</button></div></div><aside><h3>這一版的範圍</h3><ul><li>每個旅程使用一種幣別</li><li>2–20 位旅伴，由你統一記帳</li><li>最多 300 筆支出、200 筆還款</li><li>收據每張 1 MB，旅程合計 8 MB</li></ul><p>備份內含完整帳務與收據，請保存在自己的安全位置。</p></aside></section></TabsContent>
      </Tabs></>}
      <footer>TripLedger · 旅途一起走，帳目輕鬆記。</footer>
    </main>
    <Dialog open={!!editing} onOpenChange={open=>!busy&&!open&&setEditing(null)}><DialogContent className="ledger-dialog"><DialogTitle>更正支出</DialogTitle><DialogDescription>{formTrip?.name} · 更正後會重新計算餘額</DialogDescription>{actionError&&<p className="error" role="alert">{actionError} · 輸入仍保留</p>}{editing&&formTrip&&<ExpenseForm key={editing.id} trip={formTrip} expense={editing} busy={busy} submit={data=>run(async()=>{await mutate("edit-expense",data,formTrip);setEditing(null);toast.success("更正已儲存，原始內容保留於歷史");})}/>}</DialogContent></Dialog>
    <Dialog open={managing} onOpenChange={open=>!busy&&setManaging(open)}><DialogContent className="ledger-dialog"><DialogTitle>管理旅程</DialogTitle><DialogDescription>整理旅程名稱與封存狀態，所有帳目都會保留。</DialogDescription>{actionError&&<p className="error" role="alert">{actionError}</p>}{managing&&formTrip&&<TripSettings key={formTrip.id} trip={formTrip} busy={busy} submit={(action,data)=>run(async()=>{await mutate(action,data,formTrip);setManaging(false);toast.success("旅程已更新");})}/>}</DialogContent></Dialog>
    <Dialog open={creating} onOpenChange={setCreating}><DialogContent className="ledger-dialog"><DialogTitle>建立旅程</DialogTitle><DialogDescription>加入這次一起分攤的旅伴。旅伴名稱是帳務標記，不會寄出邀請。</DialogDescription>{creating&&<CreateForm busy={busy} submit={data=>run(async()=>{changed((await api("trips",data)).trip);setCreating(false);setTab("expenses");toast.success("旅程已建立");})}/>}</DialogContent></Dialog>
    <Dialog open={adding} onOpenChange={open=>!busy&&setAdding(open)}><DialogContent className="ledger-dialog"><DialogTitle>記一筆支出</DialogTitle><DialogDescription>{formTrip?.name} · {formTrip?.currency}</DialogDescription>{actionError&&<p className="error" role="alert">{actionError} · 輸入仍保留</p>}{adding&&formTrip&&<ExpenseForm trip={formTrip} busy={busy} submit={data=>run(async()=>{await mutate("expense",data,formTrip);setAdding(false);setTab("expenses");toast.success("支出已儲存");})}/>}</DialogContent></Dialog>
    <Dialog open={!!repaying} onOpenChange={open=>!open&&setRepaying(null)}><DialogContent className="ledger-dialog"><DialogTitle>記錄已還款</DialogTitle><DialogDescription>{repaying&&`${(formTrip?.members.find(m=>m.id===repaying.fromId)?.name??"")} → ${(formTrip?.members.find(m=>m.id===repaying.toId)?.name??"")}`}，僅記錄已實際完成的款項。</DialogDescription>{repaying&&formTrip&&<RepaymentForm key={repaying.id} trip={formTrip} draft={repaying} busy={busy} submit={data=>run(async()=>{await mutate("repayment",data,formTrip);setRepaying(null);toast.success("還款已記錄，餘額已更新");})}/>}</DialogContent></Dialog>
    <Dialog open={importing} onOpenChange={setImporting}><DialogContent className="ledger-dialog"><DialogTitle>匯入旅程備份</DialogTitle><DialogDescription>選擇 TripLedger 匯出的 JSON 完整備份。若同一旅程已存在，系統會拒絕覆蓋。</DialogDescription>{importing&&<ImportForm busy={busy} submit={data=>run(async()=>{changed((await api("import",data)).trip);setImporting(false);setTab("expenses");toast.success("旅程與收據已完整還原");})}/>}</DialogContent></Dialog>
    <Dialog open={!!backupView} onOpenChange={open=>!open&&setBackupView(null)}><DialogContent className="ledger-dialog"><DialogTitle>完整旅程備份</DialogTitle><DialogDescription>若瀏覽器無法下載，請複製全部內容，以 UTF-8 純文字另存為 .json 檔。內容包含帳務與收據原檔。</DialogDescription>{backupView&&<div className="form-stack"><p className="small muted break-all">建議檔名：{backupView.filename}</p><label className="field">完整備份 JSON<textarea readOnly value={backupView.text} spellCheck={false} style={{height:"40dvh",fontFamily:"monospace",fontSize:12}} onFocus={e=>e.currentTarget.select()}/></label><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(backupView.text);toast.success("完整備份已複製");}catch{toast.error("瀏覽器無法自動複製，請在內容欄位全選後手動複製");}}}>複製全部內容</button></div>}</DialogContent></Dialog>
    <AlertDialog open={!!voiding} onOpenChange={open=>!open&&setVoiding(null)}><AlertDialogContent className="ledger-dialog"><AlertDialogTitle>作廢這筆紀錄？</AlertDialogTitle><AlertDialogDescription>「{voiding?.title}」將不再計入餘額。原始紀錄與收據仍會保留，方便日後核對。支出若只是填寫錯誤，也可以取消並使用更正功能。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>保留紀錄</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void run(async()=>{if(!voiding)return;await mutate(voiding.action,{id:voiding.id},formTrip);setVoiding(null);toast.success("紀錄已作廢");});}}>確認作廢</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
