"use client";
import { Check, ArrowRight, Trash2 } from 'lucide-react';
import { balances, suggestions, formatMoney } from '@/lib/domain.mjs';
import type { Trip,Repayment } from '@/lib/types';
export function RepaymentPanel({trip,busy,onCreate,onVoid,onAction}:{trip:Trip;busy:boolean;onCreate:(r:Partial<Repayment>&{id:string})=>void;onVoid:(r:Repayment)=>void;onAction:(action:string,data:unknown)=>void}) {
  const b=balances(trip),money=(n:number)=>formatMoney(n,trip.currency),name=(id:string)=>trip.members.find(m=>m.id===id)?.name??'未知旅伴';
  const actor=(id:string|null)=>trip.team.actors.find(a=>a.id===id)?.name??'舊版未記錄';
  const admin=trip.me.role==='admin',write=trip.me.role!=='viewer'&&!trip.archived;
  const status={pending:'等待收款方確認',confirmed:'已確認',cancelled:'已取消',rejected:'已拒絕'};
  return <div className="balance-layout"><section className="panel"><div className="section-head"><h2>旅伴餘額</h2><span className="small muted">只扣除已確認還款；已移除旅伴仍保留舊帳</span></div>{trip.members.map((m,i)=><div className="member-row" key={m.id}><span className={`avatar avatar-${i%4}`}>{m.name.slice(0,1)}</span><div className="member-name"><b>{m.name}{m.active===false?'（已移除）':''}</b><small>{b[m.id]>0?'應收回':b[m.id]<0?'應付出':'已結清'}</small></div><strong className={b[m.id]>0?'positive':b[m.id]<0?'negative':'muted'}>{money(Math.abs(b[m.id]))}</strong></div>)}</section>
  <section className="panel"><div className="section-head"><h2>建議還款</h2><span className="pill">{suggestions(trip).length} 筆</span></div>{suggestions(trip).map((r:{fromId:string;toId:string;amount:number})=>{const pending=trip.repayments.filter(p=>p.status==='pending'&&(p.fromId===r.fromId||p.toId===r.toId));return <div className="suggestion" key={`${r.fromId}-${r.toId}`}><div className="row"><span>{name(r.fromId)} <ArrowRight size={14} className="inline"/> {name(r.toId)}</span><b>{money(r.amount)}</b></div>{!!pending.length&&<p className="small muted">相關旅伴有 {pending.length} 筆還款待確認，餘額尚未扣除。</p>}{write&&(admin||trip.me.participantId===r.fromId)&&<button className="secondary" disabled={busy} onClick={()=>onCreate({...r,id:crypto.randomUUID()})}><Check size={16}/>{trip.team.enabled?'申報已付款':'記錄已還款'}</button>}</div>;})}{!suggestions(trip).length&&<div className="settled"><Check size={30}/><p>目前沒有待還款項</p></div>}<p className="small muted">{trip.team.enabled?'申報不會立即扣抵。收款方確認收到後，餘額才會更新。':'實際收到款項後再記錄。這裡只保存還款紀錄。'}</p></section>
  <section className="panel repayment-panel"><h2>還款紀錄</h2>{[...trip.repayments].reverse().map(r=>{
    const receiver=trip.me.participantId===r.toId,bound=trip.teamMembers.some(a=>a.connected&&a.active&&a.participantId===r.toId),proxy=admin&&!bound,canConfirm=write&&(receiver||proxy);
    const send=(action:string)=>onAction(action,{id:r.id,operationId:crypto.randomUUID(),revision:trip.revision});
    return <article className={`repayment-entry ${r.voided?'voided':''}`} key={r.id}><div className="repayment-row"><div><b>{name(r.fromId)} → {name(r.toId)}</b><small>{r.date} · {r.voided?'已作廢':status[r.status]} · {actor(r.createdBy)} 記錄</small></div><strong>{money(r.amount)}</strong>{r.status==='confirmed'&&!r.voided&&write&&admin&&<button className="icon-button" disabled={busy} aria-label={`作廢 ${name(r.fromId)} 的還款`} onClick={()=>onVoid(r)}><Trash2 size={16}/></button>}</div>{r.status==='pending'&&<div className="repayment-actions">{canConfirm&&<><button className="primary" disabled={busy} onClick={()=>send('confirm-repayment')}>{receiver?'確認已收到款項':'代收款方確認已收到'}</button><button className="secondary" disabled={busy} onClick={()=>send('reject-repayment')}>未收到，拒絕申報</button></>}{write&&(admin||receiver||r.createdBy===trip.me.actorId)&&<button className="secondary" disabled={busy} onClick={()=>send('cancel-repayment')}>取消申報</button>}{proxy&&canConfirm&&<p className="small muted">此收款旅伴未綁定登入帳號，管理者可代確認，操作會留下紀錄。</p>}</div>}{!!r.events.length&&<details className="change-history"><summary>還款處理歷史</summary><ol>{r.events.map(e=><li key={e.id}><b>{({confirm:'確認收到',cancel:'取消申報',reject:'拒絕申報',void:'作廢還款'})[e.action]}</b><p>{actor(e.actorId)}{e.proxy?' · 管理者代辦':''} · {new Date(e.at).toLocaleString('zh-TW')}</p></li>)}</ol></details>}</article>;
  })}{!trip.repayments.length&&<p className="muted small mt-4">還沒有還款紀錄。</p>}</section></div>;
}
