"use client";
import { useCallback, useEffect, useRef, useState } from 'react';
import type { Trip,TeamActor,JoinRequest } from '@/lib/types';
import { Choice } from './ledger-ui';
export const roles={admin:'管理者',editor:'記帳成員',viewer:'僅檢視'};
const companionOptions=(trip:Trip)=>trip.members.map(member=>({value:member.id,label:member.active===false?`${member.name}（已移除，可結清舊帳）`:member.name}));
const companionName=(trip:Trip,id:string|null)=>{const member=trip.members.find(item=>item.id===id);return member?`${member.name}${member.active===false?'（已移除）':''}`:'未綁定財務旅伴';};
type Send=(action:string,data:unknown)=>Promise<void>;
type Report=(id:string,dirty:boolean)=>void;
function useDraft(id:string,dirty:boolean,report:Report){useEffect(()=>{report(id,dirty);return()=>report(id,false);},[id,dirty,report]);}
function Approval({request,trip,busy,send,report}:{request:JoinRequest;trip:Trip;busy:boolean;send:Send;report:Report}) {
  const [role,setRole]=useState('editor'),[participantId,setParticipant]=useState('__unbound__'),[revision,setRevision]=useState(trip.revision);const stale=revision!==trip.revision;
  useDraft(request.id,role!=='editor'||participantId!=='__unbound__',report);
  return <div className="team-card">{stale&&<div className="notice"><p>帳本已有更新，選擇仍保留。請重新核對申請人、權限及旅伴。</p><button className="secondary" onClick={()=>setRevision(trip.revision)}>已核對，保留選擇</button></div>}<b>{request.name}</b><p className="small muted">{request.email||'請向對方核對申請'} · {new Date(request.createdAt).toLocaleString('zh-TW')}</p><Choice label={`核准 ${request.name} 的權限`} value={role} onChange={value=>{setRole(value);if(value==='viewer')setParticipant('__unbound__');}} options={[{value:'editor',label:roles.editor},{value:'viewer',label:roles.viewer}]}/>{role!=='viewer'&&<Choice label={`將 ${request.name} 對應到旅伴`} value={participantId} onChange={setParticipant} options={[{value:'__unbound__',label:'暫不綁定'},...companionOptions(trip)]}/>}<div className="row"><button className="primary" disabled={busy||stale||trip.archived} onClick={()=>void send('approve-join',{id:request.id,revision,role,participantId:participantId==='__unbound__'?null:participantId})}>核准 {request.name}</button><button className="secondary" disabled={busy||stale} onClick={()=>void send('reject-join',{id:request.id,revision})}>拒絕申請</button></div></div>;
}
function Person({person,trip,busy,send,report}:{person:TeamActor&{connected:boolean;isOwner:boolean};trip:Trip;busy:boolean;send:Send;report:Report}) {
  const [role,setRole]=useState(person.role),[participantId,setParticipant]=useState(person.participantId??'__unbound__'),[revision,setRevision]=useState(trip.revision);const stale=revision!==trip.revision;
  const [touched,setTouched]=useState(false);
  const differs=role!==person.role||participantId!==(person.participantId??'__unbound__');
  useEffect(()=>{if(!touched||!differs){setTouched(false);setRole(person.role);setParticipant(person.participantId??'__unbound__');setRevision(trip.revision);}},[touched,differs,person.role,person.participantId,trip.revision]);
  useDraft(person.id,touched&&differs,report);
  const editable=trip.me.role==='admin'&&(trip.me.isOwner||person.role!=='admin'||person.id===trip.me.actorId);
  return <div className="team-card"><div className="row"><b>{person.name}{person.id===trip.me.actorId?'（你）':''}</b><span className="pill">{person.isOwner?'建立者':roles[person.role]}</span></div><p className="small muted">{person.connected?'已加入':person.active?'來源歷史身分，尚未重新授權':'已退出／移除'} · {companionName(trip,person.participantId)}</p>{editable&&person.connected&&<>{stale&&<div className="notice"><p>帳本已有更新。此成員目前為 {roles[person.role]}，對應旅伴：{companionName(trip,person.participantId)}。你的選擇仍保留。</p><button className="secondary" onClick={()=>setRevision(trip.revision)}>已核對，保留選擇</button></div>}<Choice label={`${person.name} 的角色`} value={role} onChange={value=>{setTouched(true);setRole(value as TeamActor['role']);if(value==='viewer')setParticipant('__unbound__');}} options={(person.isOwner?['admin']:trip.me.isOwner?['admin','editor','viewer']:person.role==='admin'?['admin']:['editor','viewer']).map(r=>({value:r,label:roles[r as keyof typeof roles]}))}/>{role!=='viewer'&&<Choice label={`${person.name} 對應的旅伴`} value={participantId} onChange={value=>{setTouched(true);setParticipant(value);}} options={[{value:'__unbound__',label:'未綁定'},...companionOptions(trip)]}/>}<div className="row"><button className="secondary" disabled={busy||stale} onClick={()=>void send('change-member',{id:person.id,revision,role,participantId:participantId==='__unbound__'?null:participantId})}>儲存成員設定</button>{!person.isOwner&&(trip.me.isOwner||person.role!=='admin')&&<button className="secondary danger-text" disabled={busy||stale} onClick={()=>void send('remove-member',{id:person.id,revision})}>移除存取</button>}</div></>}</div>;
}
export function TeamPanel({trip,mode,busy,inviteLink,send,onDirtyChange}:{trip:Trip;mode:string;busy:boolean;inviteLink:string;send:Send;onDirtyChange?:(dirty:boolean)=>void}) {
  const drafts=useRef(new Set<string>());
  const report=useCallback<Report>((id,dirty)=>{if(dirty)drafts.current.add(id);else drafts.current.delete(id);onDirtyChange?.(drafts.current.size>0);},[onDirtyChange]);
  const admin=trip.me.role==='admin';
  return <section className="panel"><div className="section-head"><h2>共同記帳</h2><span className="pill">你的權限：{roles[trip.me.role]}</span></div><p className="muted">登入帳號需經管理者核准才能查看帳本。財務旅伴可不登入；綁定後才能以該旅伴身分申報或確認還款。</p>{mode==='standalone'?<p className="notice">此自架版本目前採單一管理者登入。來源的成員歷史會保留，但原登入與邀請不會自動恢復。</p>:<>
    {admin&&<><div className="team-invite"><h3>邀請旅伴</h3><p className="small muted">連結 7 天內有效，只能申請一次。請自行分享給對方，核對申請人後再核准。新還款須由收款方確認。</p><button className="primary" disabled={busy||trip.archived} onClick={()=>void send('create-invite',{id:crypto.randomUUID()})}>建立邀請連結</button>{inviteLink&&<label className="field">邀請連結（僅這次顯示）<input readOnly value={inviteLink} onFocus={e=>e.currentTarget.select()}/><button type="button" className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(inviteLink);}catch{ /* The selectable field is the manual-copy fallback. */ }}}>複製邀請連結</button><small>若無法自動複製，請在欄位全選並複製。</small></label>}{trip.invitations?.filter(i=>!i.revoked&&!i.used&&Date.parse(i.expiresAt)>Date.now()).map(i=><div className="row" key={i.id}><span className="small">有效至 {new Date(i.expiresAt).toLocaleString('zh-TW')}</span><button className="secondary" disabled={busy} onClick={()=>void send('revoke-invite',{id:i.id})}>撤銷邀請</button></div>)}</div>
    {!!trip.joinRequests?.length&&<div className="team-section"><h3>等待核准（{trip.joinRequests.length}）</h3>{trip.joinRequests.map(r=><Approval key={r.id} request={r} trip={trip} busy={busy} send={send} report={report}/>)}</div>}</>}
    <div className="team-section"><h3>帳本成員</h3>{!trip.me.actorId&&admin&&<p className="notice">你是此帳本的管理者。建立邀請後即可設定自己對應的旅伴；匯入來源的成員需重新邀請。</p>}{trip.teamMembers.map(p=><Person key={p.id} person={p} trip={trip} busy={busy} send={send} report={report}/>)}</div>
    {!trip.me.isOwner&&<button className="secondary danger-text" disabled={busy} onClick={()=>void send('leave',{id:trip.me.actorId})}>退出此帳本</button>}
    </>}{!!trip.team.events.length&&<details className="change-history"><summary>成員異動歷史</summary><ol>{[...trip.team.events].reverse().map(e=><li key={e.id}><b>{trip.team.actors.find(a=>a.id===e.targetId)?.name}</b><p>{e.detail}</p><small>{trip.team.actors.find(a=>a.id===e.actorId)?.name??'舊版未記錄'} · {new Date(e.at).toLocaleString('zh-TW')}</small></li>)}</ol></details>}</section>;
}
export function JoinForm({initial,busy,submit,onDirtyChange}:{initial:string;busy:boolean;submit:(token:string)=>Promise<void>;onDirtyChange?:(dirty:boolean)=>void}) {
  const [value,setValue]=useState(initial),[error,setError]=useState('');
  useEffect(()=>{onDirtyChange?.(value!==initial);return()=>onDirtyChange?.(false);},[value,initial,onDirtyChange]);
  return <form className="form-stack" onSubmit={e=>{e.preventDefault();setError('');let token=value.trim();try{if(token.includes('://'))token=new URLSearchParams(new URL(token).hash.slice(1)).get('join')??'';if(!/^[a-f0-9-]{36}\.[a-f0-9-]{36}\.[a-f0-9-]{36}$/i.test(token))throw new Error('請貼上完整的帳本邀請連結或邀請碼');void submit(token);}catch(e){setError(e instanceof Error?e.message:'邀請無效');}}}><label className="field">邀請連結或邀請碼<textarea value={value} onChange={e=>setValue(e.target.value)} required maxLength={600}/></label><p className="small muted">送出後，管理者會看到你的登入名稱與 Email；核准前不會顯示帳目。</p>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'正在送出…':'申請加入帳本'}</button></form>;
}
